#!/usr/bin/env bash
# Bash script to installs nginx web server service.
# -y is to skip confirmation.
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
