#!/usr/bin/env bash
# Bash script Install and configure HAproxy on lb-01 server.
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.9
apt-get -y update
apt-get install -y haproxy=2.9.\*

echo "ENABLED=1" > /etc/default/haproxy
echo "
   listen backend_load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 440041-web-01 100.25.22.221:80 check
   server 440041-web-02 100.25.104.96:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
